### PR TITLE
Visitor logs

### PR DESCRIPTION
**Pull request by yezarela**
1. Gets Visitor Logs:
- Name
- Date of Birth (should just show Birth Date without time)
- Membership Expiry (should just show date without time)
- Login time
- Logout time
- Login successful (should show success/fail instead of true/false)

2. Edit visitor logs:
When user click edit, it should replace the value of "Login time", "Logout time", and "Login successfull" of the respective user into date pickers and checkbox. Then the edit button became save button.

3. Comment out the pagination that aren't provided by the datatable.

4. I added bootstrap fonts required by bootstrap-datetimepicker

### CODE REVIEW

**Comment by yezarela** [comment]
Thanks @haydarai, did you use the datepicker or just type into the textfield?

**Comment by haydarai** [comment]
@yezarela I’m using date picker

**Comment by dwiajik** [comment]
I do not know whether it happens only on my side and since when it happened, I cannot correctly sort and search in guest logs. But it works perfectly on approved non members

**Comment by yezarela** [comment]
Maybe related to this https://github.com/eherve/mongoose-datatable/issues/31 @dwiajik ?

**Comment by haydarai** [comment]
@yezarela is it possible to prevent user click `logoutTime` earlier than `loginTime`?

**Comment by haydarai** [comment]
@yezarela is it possible to prevent user click `logoutTime` earlier than `loginTime`?

**Pull request merged**
