### PR TITLE
Soft delete on Visitor Model

### PR DESCRIPTION
**Pull request by haydarai**
This is created due to `log.visitor` referenced to `Visitor` model. If the `visitor` is deleted sometime in the future we will unable to populate `log.visitor`. In order to make `log.visitor` still populate-able we choose to apply soft delete on Visitor model.

### CODE REVIEW

**Comment by dwiajik** [comment]
Have you installed `yarn`? Please execute `yarn` so that the `yarn.lock` will be updated
And also please rebase develop, there is a conflict with develop.

**Comment by haydarai** [comment]
@dwiajik everything is as you requested your majesty 🙇

**Comment by dwiajik** [comment]
LGTM

**Comment by dwiajik** [comment]
I like the last commit, great work

**Pull request merged**
