### PR TITLE
Fix edit non-member fields

### PR DESCRIPTION
**Pull request by yezarela**
edit non-member otherfields should be based on existing fields and available fields on table

### CODE REVIEW

**Comment by haydarai** [comment]
First bug, when no field exist before, when user click edit the label is empty and the value become `undefined`.

**Comment by haydarai** [comment]
Second bug, if there is a label, then user edit it. But save it without giving any value to it and try to re-edit again, here's what happened:

**Comment by haydarai** [comment]
Let me know if it is too difficult to do this.

**Comment by yezarela** [comment]
Oh, thanks @haydarai .. 
I've fix the bugs :)

**Comment by haydarai** [comment]
There is still a bug on this very specific scenario...
You have to have a non-registration field, and a registration field filled. Then if you press edit again, it became like this:

**Comment by yezarela** [comment]
uh oh, @haydarai I forgot to remove whitespaces..

**Comment by haydarai** [comment]
Awesome 😄

**Pull request merged**
